# Aim: Demonstrate the use of Numpy for matrix operations

In [1]:
import numpy as np

### Creating matrix / 2-D arrays

In [2]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [3]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [4]:
m1=np.array([[18,26,7],[1,2,3]])
print(m1)

[[18 26  7]
 [ 1  2  3]]


In [5]:
m2=np.array([[2,3,4],[10,20,30]])
print(m2)

[[ 2  3  4]
 [10 20 30]]


### Matirx Operations

In [6]:
# Accessing elements
print(m1[1][2])
# Range of elements
print(m1[0:1:,0:2])

3
[[18 26]]


In [7]:
# Addition is done using add() function
print(np.add(m1,m2))

[[20 29 11]
 [11 22 33]]


In [8]:
# Subtraction is done using subtract() function
print(np.subtract(m1,m2))

[[ 16  23   3]
 [ -9 -18 -27]]


In [9]:
# Element to Element multiplication is done suing multiply() function
print(np.multiply(m1,m2))

[[36 78 28]
 [10 40 90]]


In [10]:
# Product is done using dot() function
# for product, no. of columns in first matrix should be same as no. of rows in second matrix
m3=np.array([[1,2],[3,4],[5,6]])
print(m3)
print(np.dot(m1,m3))

[[1 2]
 [3 4]
 [5 6]]
[[131 182]
 [ 22  28]]


In [11]:
# Division is done using divide() function 
print(np.divide(m1,m2))

[[9.         8.66666667 1.75      ]
 [0.1        0.1        0.1       ]]


In [12]:
# square root is found using sqrt() function
x=np.array([[4,9],[16,25]])
print(x)
print(np.sqrt(x))

[[ 4  9]
 [16 25]]
[[2. 3.]
 [4. 5.]]


In [13]:
# Transpose of the matrix
print(m1.T)

[[18  1]
 [26  2]
 [ 7  3]]


In [14]:
# sum of all elements is done using sum() function
print(np.sum(m1))

57


In [15]:
# ndim is used to check the dimensions
a1=np.array([2,3])
a2=np.array(18)
print(a1.ndim)
print(a2.ndim)
print(m1.ndim)

1
0
2


In [16]:
# creating a matrix from any random integers
i=np.random.randint(0,25,25)
print(i)
# reshape is used to convert array into matrix
j=i.reshape(5,5)
print(j)

[18  4 18 12 20  1  4 19 24 14  7  0 10 21 15 13 16  2  5  5  0  9 22  5
 23]
[[18  4 18 12 20]
 [ 1  4 19 24 14]
 [ 7  0 10 21 15]
 [13 16  2  5  5]
 [ 0  9 22  5 23]]
