# Demonstrate the use of Numpy for matrix operations.

### What is NumPy and when to use it?
NumPy is a Python library allowing easy numerical calculations involving single and multidimensional arrays and matrices. NumPy excels in performing numerical calculations. Many linear algebra calculations become easy to solve using NumPy. Linear algebra is the core mathematical tool used in many Machine Learning algorithms. 

In [1]:
#Importing NumPy library
import numpy as np

#### Creating a matrix in NumPy

In [2]:
arr = np.array([[ 1, 2, 3],[ 4, 5, 6]])
print(arr)
print(arr.shape) #tells number of rows and columns in the array

[[1 2 3]
 [4 5 6]]
(2, 3)


#### Creating matrix using ranges

In [3]:
## Generate numbers from (start) to (end-1)
## Here start = 1 and end = 6
## Generated a NumPy array from 1 to 5
print(np.arange(1,6))

[1 2 3 4 5]


#### Matrix filled with zeros and ones

In [4]:
#Filling with zeros:
print(np.zeros((3, 4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
#Filling with ones:
print(np.ones((2, 2), dtype=np.int16))

[[1 1]
 [1 1]]


### Matrix Operations 

#### Addition

In [13]:
## Generate two matrices
mat_2d_1 = np.array([np.arange(0,3), np.arange(3,6)])
mat_2d_2 = np.array([np.arange(6,9), np.arange(9,12)])
print("Matrix1: \n ", mat_2d_1)
print("Matrix2: \n ", mat_2d_2)
 
## Add 1 to each element in mat_2d_1 and print it
print("Scalar addition: \n ", mat_2d_1 + 1)
 
## Add two matrices above elementwise
print("Element wise addition of two matrices of same size: \n ", mat_2d_1 + mat_2d_2)


Matrix1: 
  [[0 1 2]
 [3 4 5]]
Matrix2: 
  [[ 6  7  8]
 [ 9 10 11]]
Scalar addition: 
  [[1 2 3]
 [4 5 6]]
Element wise addition of two matrices of same size: 
  [[ 6  8 10]
 [12 14 16]]


#### Subtraction

In [14]:
## Generate two matrices
mat_2d_1 = np.array([np.arange(0,3), np.arange(3,6)])
mat_2d_2 = np.array([np.arange(6,9), np.arange(9,12)])
 
print("Matrix1: \n ", mat_2d_1)
print("Matrix2: \n ", mat_2d_2)
 
## Subtract 1 from each element in mat_2d_1 and print it
print("Scalar addition: \n ", mat_2d_1 - 1)
 
## Subtract two matrices above elementwise
print("Element wise subtraction of two matrices of same size: \n ", mat_2d_1 - mat_2d_2)


Matrix1: 
  [[0 1 2]
 [3 4 5]]
Matrix2: 
  [[ 6  7  8]
 [ 9 10 11]]
Scalar addition: 
  [[-1  0  1]
 [ 2  3  4]]
Element wise subtraction of two matrices of same size: 
  [[-6 -6 -6]
 [-6 -6 -6]]


#### Product

In [15]:
## Generate two matrices of shape (2,3) and (3,2) so that we can find
## dot product
mat_2d_1 = np.array([np.arange(0,3), np.arange(3,6)])
mat_2d_2 = np.array([np.arange(0,2), np.arange(2,4), np.arange(4,6)])
 
## Print shapes and matrices
print("Matrix1: \n ", mat_2d_1)
print("Matrix1 shape: \n", mat_2d_1.shape)
print("Matrix2: \n ", mat_2d_2)
print("Matrix2 shape: \n", mat_2d_2.shape)
 
## Multiply each element by 2 in mat_2d_1 and print it
print("Scalar Product: \n ", mat_2d_1 * 2)
 
## Find product of two matrices above using dot product
print("Dot Product: \n ", np.dot(mat_2d_1, mat_2d_2))


Matrix1: 
  [[0 1 2]
 [3 4 5]]
Matrix1 shape: 
 (2, 3)
Matrix2: 
  [[0 1]
 [2 3]
 [4 5]]
Matrix2 shape: 
 (3, 2)
Scalar Product: 
  [[ 0  2  4]
 [ 6  8 10]]
Dot Product: 
  [[10 13]
 [28 40]]


#### Division

In [16]:
## Generate a matrix of shape (2,3)
mat_2d = np.array([np.arange(0,3), np.arange(3,6)])
 
## Print the matrix
print("Matrix: \n ", mat_2d)
 
## Element wise division by scalar
print("Scalar Division: \n ", mat_2d / 2)


Matrix: 
  [[0 1 2]
 [3 4 5]]
Scalar Division: 
  [[0.  0.5 1. ]
 [1.5 2.  2.5]]


#### Transpose

In [17]:
## Generate a matrix of shape (2,3)
mat_2d = np.array([np.arange(0,3), np.arange(3,6)])
 
## Print the matrix
print("Matrix: \n ", mat_2d)
 
## Matrix Transpose
print("Transpose \n ", mat_2d.T)

Matrix: 
  [[0 1 2]
 [3 4 5]]
Transpose 
  [[0 3]
 [1 4]
 [2 5]]


#### Slicing a Matrix

In [22]:
# Create a matrix
mat_2d = np.array([np.arange(0,3), np.arange(3,6)])
print("Matrix 1: \n", mat_2d)
 
# Slice to get second row in matrix
print("Sliced row: \n ", mat_2d[1:, :])

# Slice to get last column in matrix
print("\n Sliced column: \n ", mat_2d[:, 2:])

#Slice to get (2, 2) submatrix in the centre of mat_2d i.e. [ [ 5 6] [ 9 10] ]
mat_2d_1 = np.array([np.arange(0,4), np.arange(4,8), np.arange(8,12), np.arange(12,16)])
print("\n Matrix 2: \n", mat_2d_1)
print("\n Sliced sub-matrix: \n ", mat_2d_1[1:3, 1:3])

Matrix 1: 
 [[0 1 2]
 [3 4 5]]
Sliced row: 
  [[3 4 5]]

 Sliced column: 
  [[2]
 [5]]

 Matrix 2: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

 Sliced sub-matrix: 
  [[ 5  6]
 [ 9 10]]


###### Submitted By:
       Gargi Patel
       B.Tech-CSE(BDA)
       170371