In [10]:
#Addition of Matrices
import numpy as np

A = np.array([[2, 4], [5, -6]])
B = np.array([[9, -3], [3, 6]])
C = A + B     
print(C)

[[11  1]
 [ 8  0]]


In [11]:
#Multiplication of Matrices
import numpy as np

A = np.array([[3, 6, 7], [5, -3, 0]])
B = np.array([[1, 1], [2, 1], [3, -3]])
C = A.dot(B)
print(C)

[[ 36 -12]
 [ -1   2]]


In [12]:
#Transpose of Matrices
import numpy as np

A = np.array([[1, 1], [2, 1], [3, -3]])
print(A.transpose())


[[ 1  2  3]
 [ 1  1 -3]]


In [13]:
#Access elements of a matrix
import numpy as np
A = np.array([2, 4, 6, 8, 10])

print("A[0] =", A[0])     # First element     
print("A[2] =", A[2])     # Third element 
print("A[-1] =", A[-1])   # Last element     

A[0] = 2
A[2] = 6
A[-1] = 10


In [14]:
#Access rows of a Matrix
import numpy as np

A = np.array([[1, 4, 5, 12],
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]])

print("A[0][0] =", A[0][0])  
print("A[1][2] =", A[1][2])
print("A[-1][-1] =", A[-1][-1])  

A[0][0] = 1
A[1][2] = 9
A[-1][-1] = 19


In [7]:
#Access columns of a Matrix
import numpy as np

A = np.array([[1, 4, 5, 12], 
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]])

print("A[:,0] =",A[:,0]) 
print("A[:,3] =", A[:,3])
print("A[:,-1] =", A[:,-1]) 

A[:,0] = [ 1 -5 -6]
A[:,3] = [12  0 19]
A[:,-1] = [12  0 19]


In [8]:
#Slicing of Matrix
import numpy as np
letters = np.array([1, 3, 5, 7, 9, 7, 5])

# 3rd to 5th elements
print(letters[2:5])        

# 1st to 4th elements
print(letters[:-5])       
# 6th to last elements
print(letters[5:])      

# 1st to last elements
print(letters[:])         
# reversing a list
print(letters[::-1]) 

[5 7 9]
[1 3]
[7 5]
[1 3 5 7 9 7 5]
[5 7 9 7 5 3 1]
