<a href="https://colab.research.google.com/github/ISHIKA10/Soft-Computing-Lab-2020/blob/patch-1/Matrix_Operations_with_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a= np.array([[1,2,3],[5,6,7],[8,9,0]])
b=np.array([[0,1,0],[1,1,1],[2,2,2]])


In [ ]:
# to add two matrices:
ad= np.add(a,b)
ad

array([[ 1,  3,  3],
       [ 6,  7,  8],
       [10, 11,  2]])

In [ ]:
# to subtract two matrices:
su= np.subtract(a,b)
su

array([[ 1,  1,  3],
       [ 4,  5,  6],
       [ 6,  7, -2]])

In [ ]:
# to divide two matrices:
di= np.divide(a,b)
di

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([[inf, 2. , inf],
       [5. , 6. , 7. ],
       [4. , 4.5, 0. ]])

In [ ]:
# to multiply two matrices:
mul=np.dot(a,b)
mul


array([[ 8,  9,  8],
       [20, 25, 20],
       [ 9, 17,  9]])

In [ ]:
mul2= np.multiply(a,b)
mul2

array([[ 0,  2,  0],
       [ 5,  6,  7],
       [16, 18,  0]])

In [ ]:
# to  do sqaureroot 
s=np.sqrt(a)
s


array([[1.        , 1.41421356, 1.73205081],
       [2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 0.        ]])

In [ ]:
# the summation of elements:
o=np.sum(b)
o

10

In [ ]:
# row wise summation 
r= np.sum(a,axis=1)
r

array([ 6, 18, 17])

In [ ]:
# col wise summation 
c= np.sum(a,axis=0)
c

array([14, 17, 10])

In [ ]:
#matrix transpose
t= a.T
t

array([[1, 5, 8],
       [2, 6, 9],
       [3, 7, 0]])