### Aim: Demonstrate the use of numpy for matrix operations

In [62]:
import numpy as np

### Creating an array

In [63]:
#To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray
list1=[0,1,2,3,4]
print("list1 is of tpye:",type(list1))
arr=np.array(list1) 
print("arr is of type:",type(arr))

list1 is of tpye: <class 'list'>
arr is of type: <class 'numpy.ndarray'>


In [64]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [66]:
np.ones(4)

array([1., 1., 1., 1.])

In [67]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [68]:
arr1=np.array([1,5,-3,6,1,7,3,0])
print(arr1)
type(arr1)

[ 1  5 -3  6  1  7  3  0]


numpy.ndarray

### Accessing array elements

In [69]:
a = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(a[1, 1, 2]) #Indexing
print(a[-1,-1,-1]) #Negative indexing
print(a[1,1,:]) #Slicing

12
12
[10 11 12]


### Matrix creation

In [70]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [71]:
np.ones((5,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [72]:
np.ones((4,4))*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [73]:
#2-D Arrays- An array that has 1-D arrays as its elements is called a 2-D array.
x = np.array([[1, 2], [4, 5]])
y = np.array([[7, 8], [9, 10]])
print(x)
print(y)

[[1 2]
 [4 5]]
[[ 7  8]
 [ 9 10]]


### Matrix operations

In [74]:
#  add()is used to add matrices
print ("Addition of two matrices: ")
print (np.add(x,y))

Addition of two matrices: 
[[ 8 10]
 [13 15]]


In [75]:
# subtract() is used to subtract matrices
print ("Subtraction of two matrices : ")
print (np.subtract(x,y))

Subtraction of two matrices : 
[[-6 -6]
 [-5 -5]]


In [76]:
# divide() is used to divide matrices
print ("Matrix Division : ")
print (np.divide(x,y))

Matrix Division : 
[[0.14285714 0.25      ]
 [0.44444444 0.5       ]]


In [77]:
print ("Element to Element Multiplication of two matrices: ")
print (np.multiply(x,y))

Element to Element Multiplication of two matrices: 
[[ 7 16]
 [36 50]]


In [78]:
print ("The product of two matrices : ")
print (np.dot(x,y))

The product of two matrices : 
[[25 28]
 [73 82]]


In [79]:
print ("square root is : ")
print (np.sqrt(x))

square root is : 
[[1.         1.41421356]
 [2.         2.23606798]]


In [80]:
print ("The summation of elements : ")
print (np.sum(y))

The summation of elements : 
34


In [81]:
print ("The column wise summation  : ")
print (np.sum(y,axis=0))

The column wise summation  : 
[16 18]


In [82]:
print ("The row wise summation: ")
print (np.sum(y,axis=1))

The row wise summation: 
[15 19]


In [83]:
# using "T" to transpose the matrix
print ("Matrix transposition : ")
print (x.T)

Matrix transposition : 
[[1 4]
 [2 5]]


In [84]:
#Check Number of Dimensions
#NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [85]:
#Higher Dimensional Arrays
#An array can have any number of dimensions.
#When the array is created, you can define the number of dimensions by using the ndmin argument.
arr2 = np.array([1, 2, 3, 4], ndmin=5)
print(arr2)

[[[[[1 2 3 4]]]]]


In [86]:
np.random.randint(0,100,100)
#randint returns integer value only.

array([35, 99, 97, 99, 33,  5, 16, 11, 54, 46, 42, 61, 45, 79, 54, 76, 63,
       39, 22, 71, 39,  7, 63, 20, 34, 43, 78, 84, 74, 64, 59, 63, 65, 82,
        6, 25, 86, 15, 95, 85, 26,  0, 90, 38, 30, 49,  9, 87, 17, 74, 25,
       89, 95, 10, 13, 65, 46, 59, 12, 20, 75, 42,  9, 16, 22, 12, 28, 67,
       55, 48, 30, 61, 32, 73, 77, 49, 59, 57, 55, 59, 59, 54, 45,  7, 84,
        7, 32, 93, 17, 12, 14, 30, 13, 97, 36, 11, 78, 96, 63, 99])

In [87]:
np.random.randint(0,100,100).reshape(10,10)
# reshape is used to convert array into matrix

array([[97, 72, 30, 29, 22, 20, 85,  1, 80, 50],
       [16, 18, 31, 12, 66, 35, 30,  4, 93, 15],
       [ 7, 48, 65, 12, 32, 48, 19, 51, 36, 85],
       [81, 36, 97, 78, 16, 32, 18, 25, 44, 73],
       [58, 46, 73, 82, 61, 75, 45, 44, 12, 73],
       [83, 49, 42, 14, 54,  6, 28, 78, 41, 88],
       [15, 21, 64, 56, 98, 70, 13, 20, 80, 10],
       [37, 32, 12, 81, 41, 47, 80, 70, 38, 46],
       [ 2, 93, 69, 32, 64,  5, 60, 70, 89, 40],
       [92, 57, 34, 13, 17, 45, 67, 77, 80, 33]])

In [88]:
np.random.random(25).reshape(5,5)
#return values between 0 and 1

array([[0.43921541, 0.90877734, 0.2537577 , 0.57805291, 0.50838581],
       [0.28418041, 0.52769395, 0.9557273 , 0.25337037, 0.90306218],
       [0.58443779, 0.29624581, 0.60185282, 0.74216077, 0.26062796],
       [0.34668829, 0.47722608, 0.66817015, 0.28129537, 0.70400133],
       [0.88536344, 0.3433904 , 0.85130998, 0.50986597, 0.54422691]])

In [89]:
np.random.randn(25).reshape(5,5)
# selects value from normal curve

array([[ 0.31367981,  1.31636412, -0.57792825,  0.30952935,  0.56394072],
       [ 0.07082874,  0.22066874, -2.34610442,  0.59392493, -0.04880616],
       [-0.88682475, -0.36948011, -1.46219837,  1.1644747 ,  0.96954565],
       [ 0.56602797,  0.8679641 ,  2.3148823 ,  0.22079677,  0.70961722],
       [-0.67626596,  1.42324853, -0.44180056,  0.17075514, -0.07055875]])

In [90]:
# to fix randomness,we use seed function of numpy library.
np.random.seed(52)
arr3=np.random.randint(0,100,10)
arr3

array([28, 11, 13, 23, 86, 28, 32, 69, 11, 91])

### Array operations

In [91]:
arr3.mean()

39.2

In [92]:
arr3.max()

91

In [93]:
arr3.min()

11

In [94]:
#index of maximum number
arr3.argmax()

9

In [95]:
arr3.argmin()

1

In [96]:
arr3.argsort()

array([1, 8, 2, 3, 0, 5, 6, 7, 4, 9], dtype=int64)

In [97]:
arr3.sort()

In [98]:
arr3

array([11, 11, 13, 23, 28, 28, 32, 69, 86, 91])