# Program to demonstrate the use of Numpy for matrix operations


# Creating a matrix using lists

In [1]:
import numpy as np
 
## Create a 2D numpy array using python lists
arr = np.array([[ 1, 2, 3],[ 4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


# Creating matrix using ranges

In [2]:
## Generate numbers from (start) to (end-1)
## Here start = 0
## end = 5
## Generated a NumPy array from 0 to 4
print(np.arange(0,5))

[0 1 2 3 4]


In [3]:
print(np.array([np.arange(0,5), np.arange(5,10)]))

[[0 1 2 3 4]
 [5 6 7 8 9]]


# Shape of Numpy Array

In [5]:

arr_2d = np.array([np.arange(0,5), np.arange(5,10)])
print(arr_2d.shape)

(2, 5)


# Matrix filling with zeros and ones

In [6]:
# Create a matrix of shape (3, 4) filled wit zeros
## By default float64 type of numbers are generated if not specified
print(np.zeros((3, 4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
## Create a matrix of shape (2, 2) filled with ones
## Here we have specified dtype = np.int16 which asks NumPy to generate integers
print(np.ones((2, 2), dtype=np.int16))

[[1 1]
 [1 1]]


# Matrix Operations

# Scalar Addition and Matrix Addition

In [11]:
import numpy as np
## Generate two matrices
mat_2d_1 = np.array([np.arange(0,3), np.arange(3,6)])
mat_2d_2 = np.array([np.arange(6,9), np.arange(9,12)])
print("Matrix1:  ", mat_2d_1)
print("Matrix2:  ", mat_2d_2)
 
## Add 1 to each element in mat_2d_1 and print it
print("Scalar addition: ", mat_2d_1 + 1)
 
## Add two matrices above elementwise
print("Element wise addition of two matrices of same size: n ", mat_2d_1 + mat_2d_2)

Matrix1:   [[0 1 2]
 [3 4 5]]
Matrix2:   [[ 6  7  8]
 [ 9 10 11]]
Scalar addition:  [[1 2 3]
 [4 5 6]]
Element wise addition of two matrices of same size: n  [[ 6  8 10]
 [12 14 16]]


# Subtraction

In [12]:
import numpy as np
 
## Generate two matrices
mat_2d_1 = np.array([np.arange(0,3), np.arange(3,6)])
mat_2d_2 = np.array([np.arange(6,9), np.arange(9,12)])
 
print("Matrix1: ", mat_2d_1)
print("Matrix2:", mat_2d_2)
 
## Subtract 1 from each element in mat_2d_1 and print it
print("Scalar addition:", mat_2d_1 - 1)
 
## Subtract two matrices above elementwise
print("Element wise subtraction of two matrices of same size:", mat_2d_1 - mat_2d_2)


Matrix1:  [[0 1 2]
 [3 4 5]]
Matrix2: [[ 6  7  8]
 [ 9 10 11]]
Scalar addition: [[-1  0  1]
 [ 2  3  4]]
Element wise subtraction of two matrices of same size: [[-6 -6 -6]
 [-6 -6 -6]]


# Product

In [13]:
import numpy as np
 
## Generate two matrices of shape (2,3) and (3,2) so that we can find
## dot product
mat_2d_1 = np.array([np.arange(0,3), np.arange(3,6)])
mat_2d_2 = np.array([np.arange(0,2), np.arange(2,4), np.arange(4,6)])
 
## Print shapes and matrices
print("Matrix1:", mat_2d_1)
print("Matrix1 shape:", mat_2d_1.shape)
print("Matrix2:", mat_2d_2)
print("Matrix2 shape:", mat_2d_2.shape)
 
## Multiply each element by 2 in mat_2d_1 and print it
print("Scalar Product:", mat_2d_1 * 2)
 
## Find product of two matrices above using dot product
print("Dot Product: ", np.dot(mat_2d_1, mat_2d_2))
 

Matrix1: [[0 1 2]
 [3 4 5]]
Matrix1 shape: (2, 3)
Matrix2: [[0 1]
 [2 3]
 [4 5]]
Matrix2 shape: (3, 2)
Scalar Product: [[ 0  2  4]
 [ 6  8 10]]
Dot Product:  [[10 13]
 [28 40]]


# Division

In [16]:
import numpy as np
 
## Generate a matrix of shape (2,3)
mat_2d = np.array([np.arange(0,3), np.arange(3,6)])
 
## Print the matrix
print("Matrix: n ", mat_2d)
 
## Element wise division by scalar
print("Scalar Division: n ", mat_2d / 2)

Matrix: n  [[0 1 2]
 [3 4 5]]
Scalar Division: n  [[0.  0.5 1. ]
 [1.5 2.  2.5]]


# Exponent

In [18]:
import numpy as np
 
## Generate a matrix of shape (2,3)
mat_2d = np.array([np.arange(0,3), np.arange(3,6)])
 
## Print the matrix
print("Matrix:", mat_2d)
 
## Find exponent element wise i.e. raise each element in matrix to power 2
print("Matrix raised to power of 2:", mat_2d ** 2)
 

Matrix: [[0 1 2]
 [3 4 5]]
Matrix raised to power of 2: [[ 0  1  4]
 [ 9 16 25]]


# Transpose

In [19]:
import numpy as np
 
## Generate a matrix of shape (2,3)
mat_2d = np.array([np.arange(0,3), np.arange(3,6)])
 
## Print the matrix
print("Matrix:", mat_2d)
 
## Matrix Transpose
print("Transpose", mat_2d.T)

Matrix: [[0 1 2]
 [3 4 5]]
Transpose [[0 3]
 [1 4]
 [2 5]]
