<a href="https://colab.research.google.com/github/RiyaJaipuria/Soft-Computing-Lab-2020/blob/master/Riya_Jaipuria-4th%20year-C1/Numpy%20for%20matrix%20operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Aim: Demonstrate the use of numpy for matrix operations

In [1]:

import numpy as np

Creating an array

In [2]:
#To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray
list1=[0,1,2,3,4]
print("list1 is of tpye:",type(list1))
arr=np.array(list1) 
print("arr is of type:",type(arr))

list1 is of tpye: <class 'list'>
arr is of type: <class 'numpy.ndarray'>


In [3]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.ones(4)

array([1., 1., 1., 1.])

In [6]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [7]:
arr1=np.array([1,5,-3,6,1,7,3,0])
print(arr1)
type(arr1)

[ 1  5 -3  6  1  7  3  0]


numpy.ndarray

Accessing array elements

In [8]:

a = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(a[1, 1, 2]) #Indexing
print(a[-1,-1,-1]) #Negative indexing
print(a[1,1,:]) #Slicing

12
12
[10 11 12]


Matrix creation

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones((5,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [11]:
np.ones((4,4))*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [13]:
#2-D Arrays- An array that has 1-D arrays as its elements is called a 2-D array.
x = np.array([[1, 2], [4, 5]])
y = np.array([[7, 8], [9, 10]])
print(x)
print(y)

[[1 2]
 [4 5]]
[[ 7  8]
 [ 9 10]]


Matrix Operations

In [14]:
#  add()is used to add matrices
print ("Addition of two matrices: ")
print (np.add(x,y))

Addition of two matrices: 
[[ 8 10]
 [13 15]]


In [15]:
# subtract() is used to subtract matrices
print ("Subtraction of two matrices : ")
print (np.subtract(x,y))

Subtraction of two matrices : 
[[-6 -6]
 [-5 -5]]


In [16]:
# divide() is used to divide matrices
print ("Matrix Division : ")
print (np.divide(x,y))

Matrix Division : 
[[0.14285714 0.25      ]
 [0.44444444 0.5       ]]


In [17]:
print ("Element to Element Multiplication of two matrices: ")
print (np.multiply(x,y))

Element to Element Multiplication of two matrices: 
[[ 7 16]
 [36 50]]


In [18]:
print ("The product of two matrices : ")
print (np.dot(x,y))

The product of two matrices : 
[[25 28]
 [73 82]]


In [19]:
print ("square root is : ")
print (np.sqrt(x))

square root is : 
[[1.         1.41421356]
 [2.         2.23606798]]


In [ ]:
print ("The summation of elements : ")
print (np.sum(y))

In [20]:
print ("The column wise summation  : ")
print (np.sum(y,axis=0))

The column wise summation  : 
[16 18]


In [21]:
print ("The row wise summation: ")
print (np.sum(y,axis=1))

The row wise summation: 
[15 19]


In [22]:
# using "T" to transpose the matrix
print ("Matrix transposition : ")
print (x.T)

Matrix transposition : 
[[1 4]
 [2 5]]


In [23]:
#Check Number of Dimensions
#NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [24]:
#Higher Dimensional Arrays
#An array can have any number of dimensions.
#When the array is created, you can define the number of dimensions by using the ndmin argument.
arr2 = np.array([1, 2, 3, 4], ndmin=5)
print(arr2)

[[[[[1 2 3 4]]]]]


In [25]:
np.random.randint(0,100,100)
#randint returns integer value only.

array([65, 11, 14, 32, 43, 56, 81, 95, 45, 85, 27, 93, 12, 71, 44, 57, 18,
       38, 65, 88, 26, 37, 19, 20, 45, 74,  4, 89, 94, 92, 49, 71,  7, 25,
       12,  0, 94, 63, 16, 39, 20, 26, 22, 92, 48, 61, 70, 78, 38, 26, 72,
       63, 29, 66, 82,  0, 26, 83, 39, 95, 25, 53, 12, 36, 57, 81, 63,  7,
       42, 91,  3, 78, 48, 84, 26, 92, 92, 18, 16, 69, 53, 42, 91, 82, 53,
       32, 39, 49, 39, 19, 60, 66, 71, 75, 63, 60, 30, 46, 16, 83])

In [26]:
np.random.randint(0,100,100).reshape(10,10)
# reshape is used to convert array into matrix

array([[56, 70, 38, 50, 86, 58, 16, 83, 54,  9],
       [60,  4, 68,  7, 70, 44, 87, 93,  8, 40],
       [66, 61,  2,  8,  4, 19,  5, 92, 59, 40],
       [98, 10, 55, 26, 60, 12, 54, 26, 97, 88],
       [ 6, 22, 72, 87, 39, 39,  4, 13, 90, 37],
       [21, 17, 28, 47, 17, 17, 28, 91, 32, 25],
       [33, 19, 71,  1, 63,  6, 41, 15, 72, 69],
       [98, 47, 35, 52, 94, 22, 61, 11, 95, 45],
       [56, 39, 53, 19, 17, 84, 53, 81, 67, 40],
       [29, 23, 42, 93, 16, 57, 35, 32, 92, 27]])

In [ ]:
np.random.random(25).reshape(5,5)
#return values between 0 and 1

In [27]:
np.random.randn(25).reshape(5,5)
# selects value from normal curve

array([[-0.43202938, -0.27515914, -0.21856724,  0.73654515,  0.01261335],
       [-1.39277254, -0.95682677, -0.7320028 , -1.68494069, -0.39256739],
       [-0.03097994,  0.28196276, -1.07215222, -0.47777811,  0.25078983],
       [-0.36785089, -0.7544625 ,  1.1464285 , -3.19569745, -0.11300649],
       [ 0.22389614, -1.21938562, -0.41859028, -0.98714085, -0.63947894]])

In [28]:
# to fix randomness,we use seed function of numpy library.
np.random.seed(52)
arr3=np.random.randint(0,100,10)
arr3

array([28, 11, 13, 23, 86, 28, 32, 69, 11, 91])


Array operations

In [29]:
arr3.mean()

39.2

In [30]:
arr3.max()

91

In [31]:
arr3.min()

11

In [32]:
#index of maximum number
arr3.argmax()

9

In [33]:
arr3.argmin()

1

In [34]:
arr3.argsort()

array([1, 8, 2, 3, 0, 5, 6, 7, 4, 9])

In [36]:
arr3.sort()

In [38]:
arr3

array([11, 11, 13, 23, 28, 28, 32, 69, 86, 91])