AIM: Demonstrate the use of numpy for matrix operations

Numpy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays.

In [1]:
import numpy as np

Creating an array

In [2]:
list1=[0,1,2,3,4]
print("list1 is of tpye:",type(list1))
arr=np.array(list1) 
print("arr is of type:",type(arr))

list1 is of tpye: <class 'list'>
arr is of type: <class 'numpy.ndarray'>


In [3]:
import numpy as np
 
arr = np.array([1, 2, 3])
print("Array with Rank 1: \n",arr)
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Array with Rank 2: \n", arr)
arr = np.array((1, 3, 2))
print("\nArray created using "
      "passed tuple:\n", arr)

Array with Rank 1: 
 [1 2 3]
Array with Rank 2: 
 [[1 2 3]
 [4 5 6]]

Array created using passed tuple:
 [1 3 2]


In [4]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [5]:
np.ones(4)

array([1., 1., 1., 1.])

In [6]:
arr1=np.array([1,5,-3,3,1,7,3,0])
print(arr1)
type(arr1)

[ 1  5 -3  3  1  7  3  0]


numpy.ndarray

In [7]:
a = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(a[1, 1, 2]) #Indexing
print(a[-1,-1,-1]) #Negative indexing
print(a[1,1,:]) #Slicing

12
12
[10 11 12]


In [9]:
#Creation of Matrix

In [10]:
# Generate numbers from (start) to (end-1)
# Generated a NumPy array from 0 to 4
print(np.arange(0,5))

[0 1 2 3 4]


Matrix Operations

In [12]:
arr1 = np.array([[4, 7], [2, 6]],dtype = np.float64)
arr2 = np.array([[3, 6], [2, 8]],dtype = np.float64) 

Sum = np.add(arr1, arr2)
print("Addition of Two Arrays: ")
print(Sum)

Addition of Two Arrays: 
[[ 7. 13.]
 [ 4. 14.]]


In [13]:
print ("Subtraction of two matrices : ")
print (np.subtract(arr1,arr2))

Subtraction of two matrices : 
[[ 1.  1.]
 [ 0. -2.]]


In [14]:
print ("Matrix Division : ")
print (np.divide(arr1,arr2))

Matrix Division : 
[[1.33333333 1.16666667]
 [1.         0.75      ]]


In [15]:
print ("Element to Element Multiplication of two matrices: ")
print (np.multiply(arr1,arr2))

Element to Element Multiplication of two matrices: 
[[12. 42.]
 [ 4. 48.]]


In [16]:
print ("The product of two matrices : ")
print (np.dot(arr1,arr2))

The product of two matrices : 
[[26. 80.]
 [18. 60.]]


In [17]:
print ("square root is : ")
print (np.sqrt(arr2))

square root is : 
[[1.73205081 2.44948974]
 [1.41421356 2.82842712]]


In [18]:
print ("The column wise summation  : ")
print (np.sum(arr2,axis=0))

The column wise summation  : 
[ 5. 14.]


In [19]:
print ("The row wise summation: ")
print (np.sum(arr2,axis=1))

The row wise summation: 
[ 9. 10.]


In [20]:
print ("Matrix transposition : ")
print (arr1.T)

Matrix transposition : 
[[4. 2.]
 [7. 6.]]
