# Numpy Array
### Numpy is a package for scientific computing which has support for a powerful N-dimensional array object

In [1]:
# importing numpy for matrix operations 
import numpy 
  
# initializing matrices 
x = numpy.array([[1, 2], [4, 5]]) 
y = numpy.array([[7, 8], [9, 10]]) 

In [2]:
# using add() to add matrices 
print ("The element wise addition of matrix is : ") 
print (numpy.add(x,y)) 

The element wise addition of matrix is : 
[[ 8 10]
 [13 15]]


In [3]:
# using subtract() to subtract matrices 
print ("The element wise subtraction of matrix is : ") 
print (numpy.subtract(x,y)) 

The element wise subtraction of matrix is : 
[[-6 -6]
 [-5 -5]]


In [4]:
# using divide() to divide matrices 
print ("The element wise division of matrix is : ") 
print (numpy.divide(x,y)) 

The element wise division of matrix is : 
[[0.14285714 0.25      ]
 [0.44444444 0.5       ]]


In [5]:
# multiply() and dot() 
  
# importing numpy for matrix operations 
import numpy 
  
# initializing matrices 
x = numpy.array([[1, 2], [4, 5]]) 
y = numpy.array([[7, 8], [9, 10]]) 

In [6]:
# multiply() and dot() 
  
# importing numpy for matrix operations 
import numpy 
  
# initializing matrices 
x = numpy.array([[1, 2], [4, 5]]) 
y = numpy.array([[7, 8], [9, 10]]) 

In [7]:
# using dot() to multiply matrices 
print ("The product of matrices is : ") 
print (numpy.dot(x,y)) 

The product of matrices is : 
[[25 28]
 [73 82]]


In [8]:
# importing numpy for matrix operations 
import numpy 
  
# initializing matrices 
x = numpy.array([[1, 2], [4, 5]]) 
y = numpy.array([[7, 8], [9, 10]]) 

In [9]:
# using sqrt() to print the square root of matrix 
print ("The element wise square root is : ") 
print (numpy.sqrt(x)) 

The element wise square root is : 
[[1.         1.41421356]
 [2.         2.23606798]]


In [10]:
# using sum() to print summation of all elements of matrix 
print ("The summation of all matrix element is : ") 
print (numpy.sum(y)) 

The summation of all matrix element is : 
34


In [11]:
# using sum(axis=0) to print summation of all columns of matrix 
print ("The column wise summation of all matrix  is : ") 
print (numpy.sum(y,axis=0)) 

The column wise summation of all matrix  is : 
[16 18]


In [12]:
# using sum(axis=1) to print summation of all columns of matrix 
print ("The row wise summation of all matrix  is : ") 
print (numpy.sum(y,axis=1)) 

The row wise summation of all matrix  is : 
[15 19]


In [13]:
# using "T" to transpose the matrix 
print ("The transpose of given matrix is : ") 
print (x.T) 

The transpose of given matrix is : 
[[1 4]
 [2 5]]
