<a href="https://colab.research.google.com/github/shwetay58/Soft-Computing-Lab-2020/blob/master/Shweta%20Yadav-4thyear-C/ShwetaP2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

AIM:To demonstrate the use of numpy for matrix operations.

In [ ]:
import numpy as np

1.Creating an array

In [ ]:
li=[1,2,3,4,5]
print("list1 is of tpye:",type(li))
arr=np.array(li) 
print("arr is of type:",type(arr))

list1 is of tpye: <class 'list'>
arr is of type: <class 'numpy.ndarray'>


In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [ ]:
np.arange(0,10,4)

array([0, 4, 8])

In [ ]:
arr1=np.array([1,2,-3,7,-5,8,4,0])
print(arr1)
type(arr1)

[ 1  2 -3  7 -5  8  4  0]


numpy.ndarray

2.Accessing array elements

In [ ]:
s = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(s[1, 1, 2])
print(s[-1,-1,-1])
print(s[1,1,:]) 

12
12
[10 11 12]


3.Matrix creation

In [ ]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((4,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
np.ones((5,5))*3

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [ ]:
#2-D arrays
x = np.array([[1, 2], [7, 8]])
y = np.array([[6, 7], [9, 10]])
print(x)
print(y)

[[1 2]
 [7 8]]
[[ 6  7]
 [ 9 10]]


4.Matrix operations

In [ ]:
print ("Addition of two matrices: ")
print (np.add(x,y))

Addition of two matrices: 
[[ 7  9]
 [16 18]]


In [ ]:
print ("Subtraction of two matrices : ")
print (np.subtract(x,y))

Subtraction of two matrices : 
[[-5 -5]
 [-2 -2]]


In [ ]:
print ("Matrix Division : ")
print (np.divide(x,y))

Matrix Division : 
[[0.16666667 0.28571429]
 [0.77777778 0.8       ]]


In [ ]:
print ("Element to Element Multiplication of two matrices: ")
print (np.multiply(x,y))

Element to Element Multiplication of two matrices: 
[[ 6 14]
 [63 80]]


In [ ]:
print ("The product of two matrices : ")
print (np.dot(x,y))

The product of two matrices : 
[[ 24  27]
 [114 129]]


In [ ]:
print ("square root is : ")
print (np.sqrt(x))

square root is : 
[[1.         1.41421356]
 [2.64575131 2.82842712]]


In [ ]:
print ("The summation of elements : ")
print (np.sum(y))

The summation of elements : 
32


In [ ]:
print ("The column wise summation  : ")
print (np.sum(y,axis=0))

The column wise summation  : 
[15 17]


In [ ]:
print ("The row wise summation: ")
print (np.sum(y,axis=1))

The row wise summation: 
[13 19]


In [ ]:
print ("Matrix transposition : ")
print (x.T)

Matrix transposition : 
[[1 7]
 [2 8]]


In [ ]:
#Checking number of dimensions
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
#Higher dimensional arrays
arr2 = np.array([1, 2, 3, 4], ndmin=5)
print(arr2)

[[[[[1 2 3 4]]]]]
[[[[[1 2 3 4]]]]]


In [ ]:
np.random.randint(0,100,100) #returning integer value only

array([52, 40, 13, 45, 91, 54, 89, 22, 33, 99, 17, 16, 83, 93, 63, 77, 60,
       40, 37, 96, 36, 73, 90, 47,  6,  6, 27, 51, 35, 16, 86, 43, 27, 93,
       58, 83, 62, 23,  5, 11, 53,  4, 17, 16, 97, 86, 47, 77, 37, 91, 16,
       63, 22, 45, 80, 62,  4, 79, 24, 38, 16, 41, 44, 20, 88, 60, 56, 29,
       66, 57, 16, 20, 22, 50,  9, 94, 32, 65, 49, 46, 59, 83, 47, 19, 60,
       23, 53, 56, 26, 48, 69, 17, 25, 10, 63, 82, 46, 63, 60, 35])

In [ ]:
np.random.randint(0,100,100).reshape(10,10) #conerting array into matrix

array([[38, 22, 98, 37, 59, 98, 34, 89, 99, 12],
       [33, 71, 11, 52, 63, 55, 80, 55, 95, 35],
       [48, 75, 62, 97, 28, 17, 32, 87, 96,  5],
       [35, 16, 38, 13, 64, 88, 39, 66,  7, 54],
       [24, 78, 72, 40,  6, 97, 65, 86, 82, 59],
       [92, 37, 85, 32, 48, 58, 69, 89, 86, 12],
       [55, 74, 17, 73, 53, 84, 52, 60, 55, 88],
       [30, 15, 40, 74, 19, 70, 29, 53, 64, 38],
       [90, 24, 54, 57,  1, 25, 38, 23, 72, 79],
       [25, 88, 32, 43, 56, 30, 32, 18,  2, 87]])

In [ ]:
np.random.random(25).reshape(5,5) #returning values between 0-1

array([[0.22766965, 0.22974952, 0.71185546, 0.74872659, 0.68159998],
       [0.58258091, 0.25383666, 0.15615305, 0.62550957, 0.24346113],
       [0.78047046, 0.03570635, 0.44152917, 0.60871444, 0.91690115],
       [0.55220588, 0.19273855, 0.81566873, 0.31896912, 0.51221319],
       [0.59801662, 0.88153391, 0.61149105, 0.62229238, 0.2877801 ]])

In [ ]:
np.random.randn(25).reshape(5,5)

array([[ 2.37368451,  0.35155442,  0.05360192,  0.10487498,  0.12532361],
       [-0.46717835,  2.7152015 ,  1.2403066 , -0.370004  ,  1.57410576],
       [-0.60941431,  0.72015747,  0.4623562 , -0.1499697 , -0.34253691],
       [-1.10616074, -0.10593298,  0.12204132, -0.78583471,  0.02873571],
       [-0.05888931, -0.95074215, -0.14594537,  2.16916188,  1.33406604]])

In [ ]:
np.random.seed(52)
arr3=np.random.randint(0,100,10)
arr3

array([28, 11, 13, 23, 86, 28, 32, 69, 11, 91])

5.Array operations

In [ ]:
arr3.mean()

39.2

In [ ]:
arr3.max()

91

In [ ]:
arr3.min()

11

In [ ]:
arr3.argmax()

9

In [ ]:
arr3.argmin()

1

In [ ]:
arr3.argsort()

array([1, 8, 2, 3, 0, 5, 6, 7, 4, 9])

In [ ]:
arr3.sort()

In [ ]:
arr3

array([11, 11, 13, 23, 28, 28, 32, 69, 86, 91])